name: goclockify
version: determined-by-version-script
version-script: go run cmd/goclockify/main.go --version
summary: A terminal based client for Clockify time tracker
description: |
  CLI client for Clockify time tracker.
license: MIT
icon: assets/logo-snap.png

confinement: strict
grade: stable
base: core18

parts:
  goclockify:
    source: .
    plugin: go
    go-importpath: github.com/abgeo/goclockify
    build-packages:
      - git-core
      - gcc

apps:
  goclockify:
    command: bin/goclockify
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
